/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */

	//enable clock to port bus i.e AHB1
	uint32_t *pClkPtr = (uint32*)0x40023830;
	uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;

	//step 1 : identify the free GPIO : identified for rows: PD0,PD1,PD2,PD3 columns: PD8,PD9,PD10,PD11

	//step 2 : pointers for rows and colums
	uint32_t pPD0 = (uint32*)

	for(;;);
}
